### ISSUE TITLE
Small Gear

### ISSUE THREAD

**Issue by mcanet** [BCN3D/CAD#1]
The small gear the shaft it is a little moving with Nema17 and in my printer after few prints this piece stop functioning since turn inside shaft. I think should be 5% smaller to be totally fix on the place and resist better higher tensions. I did try just to scale 5% and works the shaft although it is not a functional piece since gear teeth gets too small: https://github.com/reprapbcn/CAD/blob/master/BCN3D%2B/Printed%20Parts/STL/BCN3D1.2-M05C01.0P03A%20Small%20gear.STL

**Comment by kitusmark** [comment]
Hi @mcanet. First of all thanks for the feedback. 

We are aware of this thing but it's quite difficult to adjust the tolerances in this fabrication system. There's a lot of variability in the manufacturing process. The diameter is the minimum needed to insert the shaft without to many force.
Try to tighten the screw every "X" prints or modify the part as you want. 

If you modify it don'e forget to tell us about.
